#ifndef _SMARTRF_SETTINGS_PREDEFINED_H_
#define _SMARTRF_SETTINGS_PREDEFINED_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.13.1 (build #174)
// Compatible with SimpleLink SDK version: CC2640R2 SDK 3.20.xx.xx
// Device: CC2640R2F Rev. F (2.5)
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define RF_PROP_TX_POWER_TABLE_SIZE 14

// TX Power Table Object
extern RF_TxPowerTable_Entry RF_PROP_txPowerTable[];

// RF Core API commands
/* RF command pointers for easylink */

extern RF_Mode RF_prop_2_4G_fsk;

extern rfc_CMD_PROP_RADIO_SETUP_t RF_cmdPropRadioSetup_2_4G_fsk;
extern rfc_CMD_PROP_RADIO_SETUP_t RF_cmdPropRadioSetup_2_4G_fsk_100;

extern rfc_CMD_FS_t RF_cmdFs_preDef;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx_preDef;
extern rfc_CMD_PROP_RX_ADV_t RF_cmdPropRxAdv_preDef;

// RF Core API Overrides
extern uint32_t pOverrides_fsk[];
extern uint32_t pOverrides_fsk_100[];

#endif // _SMARTRF_SETTINGS_PREDEFINED_H_
